export const Users = [
    {
      id:1,
      profilePicture: "/images/persons/profile11.jpg",
      username: "Ifeanyi Daniel",
    },
    {
      id:2,
      profilePicture: "/images/persons/profile2.png",
      username: "James Brown",
    },
    {
      id:3,
      profilePicture: "/images/persons/profile3.jpg",
      username: "John Hillary",
    },
    {
      id:4,
      profilePicture: "/images/persons/profile4.jpg",
      username: "Emeka Obi",
    },
    {
      id:5,
      profilePicture: "/images/persons/profile5.jpg",
      username: "Nneka Okorie",
    },
    {
      id:6,
      profilePicture: "/images/persons/profile6.jpg",
      username: "Uju Blessing",
    },
    {
      id:7,
      profilePicture: "/images/persons/profile7.jpg",
      username: "Chinenye Gloria",
    },
    {
      id:8,
      profilePicture: "/images/persons/profile8.jpg",
      username: "Ogechukwu Udo",
    },
    {
      id:9,
      profilePicture: "/images/persons/profile9.jpg",
      username: "George Smith",
    },
    {
      id: 10,
      profilePicture: "/images/persons/profile10.jpg",
      username: "Ikenna Ama",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "/images/posts/beer.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "/images/posts/book.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "/images/posts/bridge.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "/images/posts/love.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "/images/posts/road.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "/images/posts/solar.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "/images/posts/sun.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "/images/posts/woman.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "/images/posts/teddy.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "/images/posts/pineapple.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];